export const EXERCISE_GROUPS = [
  {
    id: "sound",
    title: "Звучание",
    description: "Ровный звук и плавные переходы",
  },
  {
    id: "clarity",
    title: "Чёткость",
    description: "Чередование слогов на знакомых нотах",
  },
  {
    id: "height",
    title: "Высота",
    description: "Широкие интервалы в удобном диапазоне",
  },
  {
    id: "flexibility",
    title: "Гибкость",
    description: "Короткие фразы и быстрые смены нот",
  },
  {
    id: "scales",
    title: "Ступени",
    description: "Гаммы и пентатоники вверх и вниз",
  },
] as const;
export type ExerciseGroup = (typeof EXERCISE_GROUPS)[number]["id"];
export type ExerciseDefinition = {
  id: string;
  group: ExerciseGroup;
  instruction?: string;
  version: number;
  title: string;
  description: string;
  goal: "Устойчивость" | "Интонация" | "Интервалы";
  level: "Начальный" | "Средний";
  syllable: string;
  defaultBpm: number;
  minBpm: number;
  maxBpm: number;
  minBase: number;
  maxBase: number;
  notes: { interval: number; beats: number; rest: number; syllable?: string }[];
};
const steps = (intervals: number[], beats = 2, rest = 0.375) =>
  intervals.map((interval) => ({ interval, beats, rest }));
const common = {
  version: 1,
  syllable: "Ма",
  defaultBpm: 75,
  minBpm: 50,
  maxBpm: 150,
  minBase: 36,
  maxBase: 77,
} as const;
export const EXERCISES: ExerciseDefinition[] = [
  {
    ...common,
    id: "ladder",
    group: "scales",
    title: "Лесенка",
    description: "Пять ступеней вверх и обратно",
    goal: "Интонация",
    level: "Начальный",
    notes: steps([0, 2, 4, 5, 7, 5, 4, 2, 0]),
  },
  {
    ...common,
    id: "steady",
    group: "sound",
    title: "Одна нота",
    description: "Три длинных звука на одной удобной высоте",
    goal: "Устойчивость",
    level: "Начальный",
    notes: steps([0, 0, 0], 4, 1.5),
  },
  {
    ...common,
    id: "pulse",
    group: "clarity",
    title: "Повтор ноты",
    description: "Возвращайтесь к одной высоте после короткой паузы",
    goal: "Устойчивость",
    level: "Начальный",
    notes: steps([0, 0, 0, 0, 0, 0], 1.5, 0.5),
  },
  {
    ...common,
    id: "descent",
    group: "sound",
    title: "Вниз по ступеням",
    description: "Плавно опускайтесь от пятой ступени к первой",
    goal: "Интонация",
    level: "Начальный",
    notes: steps([7, 5, 4, 2, 0]),
  },
  {
    ...common,
    id: "thirds",
    group: "height",
    title: "Через ступень",
    description: "Слушайте и повторяйте переходы на терцию",
    goal: "Интервалы",
    level: "Средний",
    notes: steps([0, 4, 0, 4, 2, 5, 2, 5]),
  },
  {
    ...common,
    id: "melody",
    group: "flexibility",
    title: "Маленькая мелодия",
    description: "Соедините знакомые ступени в короткую фразу",
    goal: "Интонация",
    level: "Средний",
    notes: steps([0, 2, 4, 0, 4, 5, 7, 4, 2, 0], 1.5, 0.375),
  },
  {
    ...common,
    id: "soft-descent",
    group: "sound",
    title: "Мягкий спуск",
    description: "Сохраняйте одинаковый слог, плавно переходя вниз.",
    instruction: "Сохраняйте одинаковый слог, плавно переходя вниз.",
    syllable: "Ня",
    goal: "Интонация",
    level: "Начальный",
    notes: [
      { interval: 7, beats: 2, rest: 0.375, syllable: "Ня" },
      { interval: 5, beats: 2, rest: 0.375, syllable: "Ня" },
      { interval: 4, beats: 2, rest: 0.375, syllable: "Ня" },
      { interval: 2, beats: 2, rest: 0.375, syllable: "Ня" },
      { interval: 0, beats: 2, rest: 0.375, syllable: "Ня" },
    ],
  },
  {
    ...common,
    id: "two-waves",
    group: "sound",
    title: "Две волны",
    description: "Пойте каждую ноту на «Мум», сохраняя ровную громкость.",
    instruction: "Пойте каждую ноту на «Мум», сохраняя ровную громкость.",
    syllable: "Мум",
    goal: "Интонация",
    level: "Начальный",
    notes: [
      { interval: 0, beats: 2, rest: 0.375, syllable: "Мум" },
      { interval: 2, beats: 2, rest: 0.375, syllable: "Мум" },
      { interval: 4, beats: 2, rest: 0.375, syllable: "Мум" },
      { interval: 2, beats: 2, rest: 0.375, syllable: "Мум" },
      { interval: 0, beats: 2, rest: 0.375, syllable: "Мум" },
      { interval: 4, beats: 2, rest: 0.375, syllable: "Мум" },
      { interval: 7, beats: 2, rest: 0.375, syllable: "Мум" },
      { interval: 4, beats: 2, rest: 0.375, syllable: "Мум" },
      { interval: 0, beats: 2, rest: 0.375, syllable: "Мум" },
    ],
  },
  {
    ...common,
    id: "warm-arch",
    group: "sound",
    title: "Тёплая дуга",
    description: "Мягко произносите «Нюм» на каждой ступени.",
    instruction: "Мягко произносите «Нюм» на каждой ступени.",
    syllable: "Нюм",
    goal: "Интонация",
    level: "Начальный",
    notes: [
      { interval: 0, beats: 2, rest: 0.375, syllable: "Нюм" },
      { interval: 2, beats: 2, rest: 0.375, syllable: "Нюм" },
      { interval: 4, beats: 2, rest: 0.375, syllable: "Нюм" },
      { interval: 5, beats: 2, rest: 0.375, syllable: "Нюм" },
      { interval: 7, beats: 2, rest: 0.375, syllable: "Нюм" },
      { interval: 5, beats: 2, rest: 0.375, syllable: "Нюм" },
      { interval: 4, beats: 2, rest: 0.375, syllable: "Нюм" },
      { interval: 2, beats: 2, rest: 0.375, syllable: "Нюм" },
      { interval: 0, beats: 2, rest: 0.375, syllable: "Нюм" },
    ],
  },
  {
    ...common,
    id: "open-echo",
    group: "sound",
    title: "Открытое эхо",
    description: "Первую дугу пойте на «Мм», вторую — на «Ма».",
    instruction: "Первую дугу пойте на «Мм», вторую — на «Ма».",
    syllable: "Мм · Ма",
    goal: "Интонация",
    level: "Начальный",
    notes: [
      { interval: 0, beats: 2, rest: 0.375, syllable: "Мм" },
      { interval: 4, beats: 2, rest: 0.375, syllable: "Мм" },
      { interval: 7, beats: 2, rest: 0.375, syllable: "Мм" },
      { interval: 12, beats: 2, rest: 0.375, syllable: "Мм" },
      { interval: 7, beats: 2, rest: 0.375, syllable: "Мм" },
      { interval: 4, beats: 2, rest: 0.375, syllable: "Мм" },
      { interval: 0, beats: 2, rest: 0.375, syllable: "Мм" },
      { interval: 4, beats: 2, rest: 0.375, syllable: "Ма" },
      { interval: 7, beats: 2, rest: 0.375, syllable: "Ма" },
      { interval: 12, beats: 2, rest: 0.375, syllable: "Ма" },
      { interval: 7, beats: 2, rest: 0.375, syllable: "Ма" },
      { interval: 4, beats: 2, rest: 0.375, syllable: "Ма" },
      { interval: 0, beats: 2, rest: 0.375, syllable: "Ма" },
    ],
  },
  {
    ...common,
    id: "five-vowels",
    group: "clarity",
    title: "Пять гласных",
    description: "Меняйте гласную на каждой ноте, сохраняя высоту.",
    instruction: "Меняйте гласную на каждой ноте, сохраняя высоту.",
    syllable: "Ма · Мэ · Ми · Мо · Му",
    goal: "Интонация",
    level: "Начальный",
    notes: [
      { interval: 0, beats: 2, rest: 0.375, syllable: "Ма" },
      { interval: 0, beats: 2, rest: 0.375, syllable: "Мэ" },
      { interval: 0, beats: 2, rest: 0.375, syllable: "Ми" },
      { interval: 0, beats: 2, rest: 0.375, syllable: "Мо" },
      { interval: 0, beats: 2, rest: 0.375, syllable: "Му" },
      { interval: 0, beats: 2, rest: 0.375, syllable: "Ма" },
      { interval: 0, beats: 2, rest: 0.375, syllable: "Мэ" },
      { interval: 0, beats: 2, rest: 0.375, syllable: "Ми" },
      { interval: 0, beats: 2, rest: 0.375, syllable: "Мо" },
      { interval: 0, beats: 2, rest: 0.375, syllable: "Му" },
    ],
  },
  {
    ...common,
    id: "clear-steps",
    group: "clarity",
    title: "Чёткие шаги",
    description: "Чередуйте «Да», «Дэ», «Ди» по подсказкам на нотах.",
    instruction: "Чередуйте «Да», «Дэ», «Ди» по подсказкам на нотах.",
    syllable: "Да · Дэ · Ди",
    goal: "Интонация",
    level: "Начальный",
    notes: [
      { interval: 0, beats: 2, rest: 0.375, syllable: "Да" },
      { interval: 2, beats: 2, rest: 0.375, syllable: "Дэ" },
      { interval: 4, beats: 2, rest: 0.375, syllable: "Ди" },
      { interval: 5, beats: 2, rest: 0.375, syllable: "Да" },
      { interval: 7, beats: 2, rest: 0.375, syllable: "Дэ" },
      { interval: 5, beats: 2, rest: 0.375, syllable: "Ди" },
      { interval: 4, beats: 2, rest: 0.375, syllable: "Да" },
      { interval: 2, beats: 2, rest: 0.375, syllable: "Дэ" },
      { interval: 0, beats: 2, rest: 0.375, syllable: "Ди" },
    ],
  },
  {
    ...common,
    id: "light-syllables",
    group: "clarity",
    title: "Лёгкие слоги",
    description: "Чередуйте «Ля» и «Лё», не ускоряя переходы.",
    instruction: "Чередуйте «Ля» и «Лё», не ускоряя переходы.",
    syllable: "Ля · Лё",
    goal: "Интонация",
    level: "Начальный",
    notes: [
      { interval: 0, beats: 2, rest: 0.375, syllable: "Ля" },
      { interval: 4, beats: 2, rest: 0.375, syllable: "Лё" },
      { interval: 7, beats: 2, rest: 0.375, syllable: "Ля" },
      { interval: 12, beats: 2, rest: 0.375, syllable: "Лё" },
      { interval: 7, beats: 2, rest: 0.375, syllable: "Ля" },
      { interval: 4, beats: 2, rest: 0.375, syllable: "Лё" },
      { interval: 0, beats: 2, rest: 0.375, syllable: "Ля" },
    ],
  },
  {
    ...common,
    id: "lip-rhythm",
    group: "clarity",
    title: "Ритм слогов",
    description: "Пойте слоги отчётливо, оставляя короткие паузы.",
    instruction: "Пойте слоги отчётливо, оставляя короткие паузы.",
    syllable: "Ба · Бо · Бу",
    goal: "Интонация",
    level: "Начальный",
    notes: [
      { interval: 0, beats: 2, rest: 0.375, syllable: "Ба" },
      { interval: 0, beats: 2, rest: 0.375, syllable: "Бо" },
      { interval: 2, beats: 2, rest: 0.375, syllable: "Бу" },
      { interval: 2, beats: 2, rest: 0.375, syllable: "Ба" },
      { interval: 4, beats: 2, rest: 0.375, syllable: "Бо" },
      { interval: 4, beats: 2, rest: 0.375, syllable: "Бу" },
      { interval: 2, beats: 2, rest: 0.375, syllable: "Ба" },
      { interval: 2, beats: 2, rest: 0.375, syllable: "Бо" },
      { interval: 0, beats: 2, rest: 0.375, syllable: "Бу" },
    ],
  },
  {
    ...common,
    id: "octave-echo",
    group: "height",
    title: "Октавное эхо",
    description:
      "Повторите верхнюю ноту трижды. Выберите комфортную начальную высоту.",
    instruction:
      "Повторите верхнюю ноту трижды. Выберите комфортную начальную высоту.",
    syllable: "Нэй",
    goal: "Интервалы",
    level: "Средний",
    notes: [
      { interval: 0, beats: 2, rest: 0.375, syllable: "Нэй" },
      { interval: 4, beats: 2, rest: 0.375, syllable: "Нэй" },
      { interval: 7, beats: 2, rest: 0.375, syllable: "Нэй" },
      { interval: 12, beats: 2, rest: 0.375, syllable: "Нэй" },
      { interval: 12, beats: 2, rest: 0.375, syllable: "Нэй" },
      { interval: 12, beats: 2, rest: 0.375, syllable: "Нэй" },
      { interval: 7, beats: 2, rest: 0.375, syllable: "Нэй" },
      { interval: 4, beats: 2, rest: 0.375, syllable: "Нэй" },
      { interval: 0, beats: 2, rest: 0.375, syllable: "Нэй" },
    ],
  },
  {
    ...common,
    id: "upper-swing",
    group: "height",
    title: "Верхние качели",
    description: "Слушайте скачки между пятой ступенью и октавой.",
    instruction: "Слушайте скачки между пятой ступенью и октавой.",
    syllable: "И",
    goal: "Интервалы",
    level: "Средний",
    notes: [
      { interval: 0, beats: 2, rest: 0.375, syllable: "И" },
      { interval: 4, beats: 2, rest: 0.375, syllable: "И" },
      { interval: 7, beats: 2, rest: 0.375, syllable: "И" },
      { interval: 12, beats: 2, rest: 0.375, syllable: "И" },
      { interval: 7, beats: 2, rest: 0.375, syllable: "И" },
      { interval: 12, beats: 2, rest: 0.375, syllable: "И" },
      { interval: 7, beats: 2, rest: 0.375, syllable: "И" },
      { interval: 4, beats: 2, rest: 0.375, syllable: "И" },
      { interval: 0, beats: 2, rest: 0.375, syllable: "И" },
    ],
  },
  {
    ...common,
    id: "wide-arch",
    group: "height",
    title: "Большая дуга",
    description:
      "Широкая фраза: снизьте начальную высоту, если верхние ноты неудобны.",
    instruction:
      "Широкая фраза: снизьте начальную высоту, если верхние ноты неудобны.",
    syllable: "Го",
    goal: "Интервалы",
    level: "Средний",
    notes: [
      { interval: 0, beats: 2, rest: 0.375, syllable: "Го" },
      { interval: 4, beats: 2, rest: 0.375, syllable: "Го" },
      { interval: 7, beats: 2, rest: 0.375, syllable: "Го" },
      { interval: 12, beats: 2, rest: 0.375, syllable: "Го" },
      { interval: 16, beats: 2, rest: 0.375, syllable: "Го" },
      { interval: 19, beats: 2, rest: 0.375, syllable: "Го" },
      { interval: 16, beats: 2, rest: 0.375, syllable: "Го" },
      { interval: 12, beats: 2, rest: 0.375, syllable: "Го" },
      { interval: 7, beats: 2, rest: 0.375, syllable: "Го" },
      { interval: 4, beats: 2, rest: 0.375, syllable: "Го" },
      { interval: 0, beats: 2, rest: 0.375, syllable: "Го" },
    ],
  },
  {
    ...common,
    id: "upward-light",
    group: "height",
    title: "К вершине",
    description: "Поднимайтесь по ступеням и удержите последнюю ноту.",
    instruction: "Поднимайтесь по ступеням и удержите последнюю ноту.",
    syllable: "Я",
    goal: "Интервалы",
    level: "Средний",
    notes: [
      { interval: 0, beats: 2, rest: 0.375, syllable: "Я" },
      { interval: 2, beats: 2, rest: 0.375, syllable: "Я" },
      { interval: 4, beats: 2, rest: 0.375, syllable: "Я" },
      { interval: 5, beats: 2, rest: 0.375, syllable: "Я" },
      { interval: 7, beats: 2, rest: 0.375, syllable: "Я" },
      { interval: 9, beats: 2, rest: 0.375, syllable: "Я" },
      { interval: 11, beats: 2, rest: 0.375, syllable: "Я" },
      { interval: 12, beats: 2, rest: 0.375, syllable: "Я" },
    ],
  },
  {
    ...common,
    id: "three-step-run",
    group: "flexibility",
    title: "Тройной шаг",
    description:
      "Повторяйте короткую нисходящую фигуру. Начните с медленного темпа.",
    instruction:
      "Повторяйте короткую нисходящую фигуру. Начните с медленного темпа.",
    syllable: "Лу",
    goal: "Интонация",
    level: "Средний",
    notes: [
      { interval: 4, beats: 1, rest: 0.25, syllable: "Лу" },
      { interval: 2, beats: 1, rest: 0.25, syllable: "Лу" },
      { interval: 0, beats: 1, rest: 0.25, syllable: "Лу" },
      { interval: 4, beats: 1, rest: 0.25, syllable: "Лу" },
      { interval: 2, beats: 1, rest: 0.25, syllable: "Лу" },
      { interval: 0, beats: 1, rest: 0.25, syllable: "Лу" },
      { interval: 4, beats: 1, rest: 0.25, syllable: "Лу" },
      { interval: 2, beats: 1, rest: 0.25, syllable: "Лу" },
      { interval: 0, beats: 1, rest: 0.25, syllable: "Лу" },
      { interval: 4, beats: 1, rest: 0.25, syllable: "Лу" },
      { interval: 2, beats: 1, rest: 0.25, syllable: "Лу" },
      { interval: 0, beats: 2, rest: 0.25, syllable: "Лу" },
    ],
  },
  {
    ...common,
    id: "growing-wave",
    group: "flexibility",
    title: "Растущая волна",
    description: "Сохраняйте отдельную атаку каждого «Ну».",
    instruction: "Сохраняйте отдельную атаку каждого «Ну».",
    syllable: "Ну",
    goal: "Интонация",
    level: "Средний",
    notes: [
      { interval: 0, beats: 1, rest: 0.25, syllable: "Ну" },
      { interval: 2, beats: 1, rest: 0.25, syllable: "Ну" },
      { interval: 0, beats: 1, rest: 0.25, syllable: "Ну" },
      { interval: 2, beats: 1, rest: 0.25, syllable: "Ну" },
      { interval: 4, beats: 1, rest: 0.25, syllable: "Ну" },
      { interval: 2, beats: 1, rest: 0.25, syllable: "Ну" },
      { interval: 0, beats: 1, rest: 0.25, syllable: "Ну" },
      { interval: 2, beats: 1, rest: 0.25, syllable: "Ну" },
      { interval: 4, beats: 1, rest: 0.25, syllable: "Ну" },
      { interval: 5, beats: 1, rest: 0.25, syllable: "Ну" },
      { interval: 4, beats: 1, rest: 0.25, syllable: "Ну" },
      { interval: 2, beats: 1, rest: 0.25, syllable: "Ну" },
      { interval: 0, beats: 2, rest: 0.25, syllable: "Ну" },
    ],
  },
  {
    ...common,
    id: "broken-chord",
    group: "flexibility",
    title: "Звонкие дуги",
    description: "Повторите арпеджио с большой септимой в спокойном темпе.",
    instruction: "Повторите арпеджио с большой септимой в спокойном темпе.",
    syllable: "Ди",
    goal: "Интонация",
    level: "Средний",
    notes: [
      { interval: 0, beats: 1, rest: 0.25, syllable: "Ди" },
      { interval: 4, beats: 1, rest: 0.25, syllable: "Ди" },
      { interval: 7, beats: 1, rest: 0.25, syllable: "Ди" },
      { interval: 11, beats: 1, rest: 0.25, syllable: "Ди" },
      { interval: 7, beats: 1, rest: 0.25, syllable: "Ди" },
      { interval: 4, beats: 1, rest: 0.25, syllable: "Ди" },
      { interval: 0, beats: 1, rest: 0.25, syllable: "Ди" },
      { interval: 0, beats: 1, rest: 0.25, syllable: "Ди" },
      { interval: 4, beats: 1, rest: 0.25, syllable: "Ди" },
      { interval: 7, beats: 1, rest: 0.25, syllable: "Ди" },
      { interval: 11, beats: 1, rest: 0.25, syllable: "Ди" },
      { interval: 7, beats: 1, rest: 0.25, syllable: "Ди" },
      { interval: 4, beats: 1, rest: 0.25, syllable: "Ди" },
      { interval: 0, beats: 2, rest: 0.25, syllable: "Ди" },
    ],
  },
  {
    ...common,
    id: "returning-steps",
    group: "flexibility",
    title: "Шаг с возвратом",
    description: "Слушайте короткие возвраты перед следующим подъёмом.",
    instruction: "Слушайте короткие возвраты перед следующим подъёмом.",
    syllable: "Ли",
    goal: "Интонация",
    level: "Средний",
    notes: [
      { interval: 0, beats: 1, rest: 0.25, syllable: "Ли" },
      { interval: 2, beats: 1, rest: 0.25, syllable: "Ли" },
      { interval: 0, beats: 1, rest: 0.25, syllable: "Ли" },
      { interval: 2, beats: 1, rest: 0.25, syllable: "Ли" },
      { interval: 4, beats: 1, rest: 0.25, syllable: "Ли" },
      { interval: 2, beats: 1, rest: 0.25, syllable: "Ли" },
      { interval: 4, beats: 1, rest: 0.25, syllable: "Ли" },
      { interval: 5, beats: 1, rest: 0.25, syllable: "Ли" },
      { interval: 4, beats: 1, rest: 0.25, syllable: "Ли" },
      { interval: 5, beats: 1, rest: 0.25, syllable: "Ли" },
      { interval: 7, beats: 1, rest: 0.25, syllable: "Ли" },
      { interval: 5, beats: 1, rest: 0.25, syllable: "Ли" },
      { interval: 7, beats: 2, rest: 0.25, syllable: "Ли" },
    ],
  },
  {
    ...common,
    id: "major-up",
    group: "scales",
    title: "Мажор: вверх",
    description:
      "Слушайте расстояния между ступенями; последнюю ноту удержите дольше.",
    instruction:
      "Слушайте расстояния между ступенями; последнюю ноту удержите дольше.",
    syllable: "Ма",
    goal: "Интонация",
    level: "Начальный",
    notes: [
      { interval: 0, beats: 1, rest: 0.375, syllable: "Ма" },
      { interval: 2, beats: 1, rest: 0.375, syllable: "Ма" },
      { interval: 4, beats: 1, rest: 0.375, syllable: "Ма" },
      { interval: 5, beats: 1, rest: 0.375, syllable: "Ма" },
      { interval: 7, beats: 1, rest: 0.375, syllable: "Ма" },
      { interval: 9, beats: 1, rest: 0.375, syllable: "Ма" },
      { interval: 11, beats: 1, rest: 0.375, syllable: "Ма" },
      { interval: 12, beats: 2, rest: 0.375, syllable: "Ма" },
    ],
  },
  {
    ...common,
    id: "major-down",
    group: "scales",
    title: "Мажор: вниз",
    description:
      "Слушайте расстояния между ступенями; последнюю ноту удержите дольше.",
    instruction:
      "Слушайте расстояния между ступенями; последнюю ноту удержите дольше.",
    syllable: "Ма",
    goal: "Интонация",
    level: "Начальный",
    notes: [
      { interval: 12, beats: 1, rest: 0.375, syllable: "Ма" },
      { interval: 11, beats: 1, rest: 0.375, syllable: "Ма" },
      { interval: 9, beats: 1, rest: 0.375, syllable: "Ма" },
      { interval: 7, beats: 1, rest: 0.375, syllable: "Ма" },
      { interval: 5, beats: 1, rest: 0.375, syllable: "Ма" },
      { interval: 4, beats: 1, rest: 0.375, syllable: "Ма" },
      { interval: 2, beats: 1, rest: 0.375, syllable: "Ма" },
      { interval: 0, beats: 2, rest: 0.375, syllable: "Ма" },
    ],
  },
  {
    ...common,
    id: "minor-up",
    group: "scales",
    title: "Натуральный минор: вверх",
    description:
      "Слушайте расстояния между ступенями; последнюю ноту удержите дольше.",
    instruction:
      "Слушайте расстояния между ступенями; последнюю ноту удержите дольше.",
    syllable: "Ма",
    goal: "Интонация",
    level: "Начальный",
    notes: [
      { interval: 0, beats: 1, rest: 0.375, syllable: "Ма" },
      { interval: 2, beats: 1, rest: 0.375, syllable: "Ма" },
      { interval: 3, beats: 1, rest: 0.375, syllable: "Ма" },
      { interval: 5, beats: 1, rest: 0.375, syllable: "Ма" },
      { interval: 7, beats: 1, rest: 0.375, syllable: "Ма" },
      { interval: 8, beats: 1, rest: 0.375, syllable: "Ма" },
      { interval: 10, beats: 1, rest: 0.375, syllable: "Ма" },
      { interval: 12, beats: 2, rest: 0.375, syllable: "Ма" },
    ],
  },
  {
    ...common,
    id: "minor-down",
    group: "scales",
    title: "Натуральный минор: вниз",
    description:
      "Слушайте расстояния между ступенями; последнюю ноту удержите дольше.",
    instruction:
      "Слушайте расстояния между ступенями; последнюю ноту удержите дольше.",
    syllable: "Ма",
    goal: "Интонация",
    level: "Начальный",
    notes: [
      { interval: 12, beats: 1, rest: 0.375, syllable: "Ма" },
      { interval: 10, beats: 1, rest: 0.375, syllable: "Ма" },
      { interval: 8, beats: 1, rest: 0.375, syllable: "Ма" },
      { interval: 7, beats: 1, rest: 0.375, syllable: "Ма" },
      { interval: 5, beats: 1, rest: 0.375, syllable: "Ма" },
      { interval: 3, beats: 1, rest: 0.375, syllable: "Ма" },
      { interval: 2, beats: 1, rest: 0.375, syllable: "Ма" },
      { interval: 0, beats: 2, rest: 0.375, syllable: "Ма" },
    ],
  },
  {
    ...common,
    id: "major-penta-up",
    group: "scales",
    title: "Светлая пентатоника: вверх",
    description:
      "Слушайте расстояния между ступенями; последнюю ноту удержите дольше.",
    instruction:
      "Слушайте расстояния между ступенями; последнюю ноту удержите дольше.",
    syllable: "Ма",
    goal: "Интонация",
    level: "Начальный",
    notes: [
      { interval: 0, beats: 1, rest: 0.375, syllable: "Ма" },
      { interval: 2, beats: 1, rest: 0.375, syllable: "Ма" },
      { interval: 4, beats: 1, rest: 0.375, syllable: "Ма" },
      { interval: 7, beats: 1, rest: 0.375, syllable: "Ма" },
      { interval: 9, beats: 1, rest: 0.375, syllable: "Ма" },
      { interval: 12, beats: 2, rest: 0.375, syllable: "Ма" },
    ],
  },
  {
    ...common,
    id: "major-penta-down",
    group: "scales",
    title: "Светлая пентатоника: вниз",
    description:
      "Слушайте расстояния между ступенями; последнюю ноту удержите дольше.",
    instruction:
      "Слушайте расстояния между ступенями; последнюю ноту удержите дольше.",
    syllable: "Ма",
    goal: "Интонация",
    level: "Начальный",
    notes: [
      { interval: 12, beats: 1, rest: 0.375, syllable: "Ма" },
      { interval: 9, beats: 1, rest: 0.375, syllable: "Ма" },
      { interval: 7, beats: 1, rest: 0.375, syllable: "Ма" },
      { interval: 4, beats: 1, rest: 0.375, syllable: "Ма" },
      { interval: 2, beats: 1, rest: 0.375, syllable: "Ма" },
      { interval: 0, beats: 2, rest: 0.375, syllable: "Ма" },
    ],
  },
  {
    ...common,
    id: "minor-penta-up",
    group: "scales",
    title: "Мягкая пентатоника: вверх",
    description:
      "Слушайте расстояния между ступенями; последнюю ноту удержите дольше.",
    instruction:
      "Слушайте расстояния между ступенями; последнюю ноту удержите дольше.",
    syllable: "Ма",
    goal: "Интонация",
    level: "Начальный",
    notes: [
      { interval: 0, beats: 1, rest: 0.375, syllable: "Ма" },
      { interval: 3, beats: 1, rest: 0.375, syllable: "Ма" },
      { interval: 5, beats: 1, rest: 0.375, syllable: "Ма" },
      { interval: 7, beats: 1, rest: 0.375, syllable: "Ма" },
      { interval: 10, beats: 1, rest: 0.375, syllable: "Ма" },
      { interval: 12, beats: 2, rest: 0.375, syllable: "Ма" },
    ],
  },
  {
    ...common,
    id: "minor-penta-down",
    group: "scales",
    title: "Мягкая пентатоника: вниз",
    description:
      "Слушайте расстояния между ступенями; последнюю ноту удержите дольше.",
    instruction:
      "Слушайте расстояния между ступенями; последнюю ноту удержите дольше.",
    syllable: "Ма",
    goal: "Интонация",
    level: "Начальный",
    notes: [
      { interval: 12, beats: 1, rest: 0.375, syllable: "Ма" },
      { interval: 10, beats: 1, rest: 0.375, syllable: "Ма" },
      { interval: 7, beats: 1, rest: 0.375, syllable: "Ма" },
      { interval: 5, beats: 1, rest: 0.375, syllable: "Ма" },
      { interval: 3, beats: 1, rest: 0.375, syllable: "Ма" },
      { interval: 0, beats: 2, rest: 0.375, syllable: "Ма" },
    ],
  },
];
export function getExercise(id?: string): ExerciseDefinition {
  return EXERCISES.find((exercise) => exercise.id === id) ?? EXERCISES[0];
}
export function intervalBounds(exercise: ExerciseDefinition) {
  return {
    min: Math.min(...exercise.notes.map((n) => n.interval)),
    max: Math.max(...exercise.notes.map((n) => n.interval)),
  };
}
export function baseBounds(exercise: ExerciseDefinition) {
  const bounds = intervalBounds(exercise);
  return {
    min: Math.max(exercise.minBase, 36 - bounds.min),
    max: Math.min(exercise.maxBase, 84 - bounds.max),
  };
}
export const SHORT_SESSION = {
  id: "first-steps",
  title: "Первые шаги",
  description: "Удержание → ступени вниз → лесенка",
  exercises: ["steady", "descent", "ladder"],
  restSeconds: 10,
};
